set(CPACK_GENERATOR "DEB")

set(CPACK_PACKAGE_VERSION_MAJOR ${PACKAGE_MAJOR_VERSION})
set(CPACK_PACKAGE_VERSION_MINOR ${PACKAGE_MINOR_VERSION})
set(CPACK_PACKAGE_VERSION_PATCH ${PACKAGE_PATCH_VERSION})

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

set(CPACK_PACKAGE_CONTACT "gaoyichao2013@126.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "YiChao.GAO")


